### ISSUE TITLE
Hi, can it using for driven metahuman?

### ISSUE THREAD

**Issue by lucasjinreal** [ArhasGH/Maya-Live-Link-CSV-Import#3]
Hi, can it using for driven metahuman?

**Comment by aronamao** [comment]
Hey,
I personally have not worked with MetaHuman rigs but last time I briefly glossed over them they used the same system, so it should work. Just try it out and if it doesn't feel free to come back and reopen this issue.

**Comment by lucasjinreal** [comment]
@ArhasGH  thanks, but I think it's not. blend shapes in livelinkface app is not same as meta humans. However, I already fond a way to driven them. thank u.

**Comment by RikkTheGaijin** [comment]
@jinfagang hi, could you please share how did you solve the problem? I have tried @aronamao importer but like you said, its not compatible with Metahuman. Could you please tell me what did you find?
