### ISSUE TITLE
Maya 2020.5 - No menu/launcher when loaded

### ISSUE THREAD

**Issue by Alaztor10** [ArhasGH/Maya-Live-Link-CSV-Import#4]
Maya 2020.5 doesn't show any indicators to launch the plugin application.  
Plugin is detected and loads correctly through plugin-manager, but there is no additional menu's/shelfs/commands available to use.

Is there any commands we can execute through script to initiate?

**Comment by aronamao** [comment]
Hey there, the plug-in does not come with a UI, instead it just allows you to import .csv files like any other file. So either through the import menu or simple drag & drop.
